export const projects = [
  {
    id: 1,
    type: 'website',
    date: '3/1/2022',
    title: 'TechTutz.com',
    link: 'https://techtutz.com/',
    description: 'Web development learning website built in React 18. Sections of educational information and interactable content for HTML, CSS, and JS.',
  },
  {
    id: 2,
    type: 'game',
    date: '10/24/2023',
    title: 'Deadwood Drive (demo)',
    link: 'https://castlecraftstudios.itch.io/deadwood-drive-alpha-demo-v1-5-0',
    description: `A low-poly driving game (with a twist) made with Unity. Solo game development project to start my game-dev journey.`,
  },
  {
    id: 3,
    type: 'code',
    date: '6/9/2022',
    title: 'React Component Library',
    link: 'https://github.com/kaydenhardcastle/shared-component-library',
    description: "A simple set of re-usable components built in React 18. Accompanied by a YouTube series under the TechTutz channel.",
  },
  {
    id: 4,
    type: 'code',
    date: '3/2/2021',
    title: 'React Budget App',
    link: 'https://github.com/kaydenhardcastle/react-budget-app',
    description: "A simple budget tracking app built in React 17. Accompanied by a YouTube series under the TechTutz channel.",
  },
  {
    id: 5,
    type: 'code',
    date: '11/2/2022',
    title: 'Three JS Fun',
    link: 'https://github.com/kaydenhardcastle/three-js-demo',
    description: "A project showing the use of Three JS modelling in vanilla JS and React 18.",
  },
  {
    id: 6,
    type: 'code',
    date: '11/2/2022',
    title: 'React Typescript Intro',
    link: 'https://github.com/kaydenhardcastle/react-ts-intro',
    description: "A project showing the basic use of Typescript in React 18.",
  },
  {
    id: 7,
    type: 'youtube',
    date: '5/1/2019',
    title: 'Kayden Hardcastle',
    link: 'https://www.youtube.com/@kaydenhardcastle',
    description: "My personal YouTube channel.",
  },
  {
    id: 8,
    type: 'youtube',
    date: '10/10/2023',
    title: 'CastleCraftStudios',
    link: 'https://www.youtube.com/@castlecraftstudios',
    description: "My game development YouTube channel.",
  },
  {
    id: 9,
    type: 'youtube',
    date: '10/1/2022',
    title: 'TechTutz',
    link: 'https://www.youtube.com/@techtutz',
    description: "My software development YouTube channel.",
  },
  {
    id: 10,
    type: 'music',
    date: '3/21/23',
    title: 'What Happens Next (demo)',
    link: 'https://www.youtube.com/watch?v=RkPLhmThExA&list=OLAK5uy_nOyAsMlqV5wEv6xIWfWgwf1fLf8yhzuLo',
    description: "My first single release as a solo artist.",
  },
  {
    id: 11,
    type: 'music',
    date: '11/26/2015',
    title: 'Black Life Unique',
    link: 'https://www.reverbnation.com/blacklifeunique',
    description: "The band I was in during early to mid college. Had a blast travelling around and released some music as well.",
  },
  {
    id: 12,
    type: 'music',
    date: '1/11/2024',
    title: 'What Happens Next (LP)',
    link: 'https://www.youtube.com/watch?v=DztC2krng7U&list=OLAK5uy_kNyjp-OEGeRWtm2g5RuTN40gr8ZhaBeRc',
    description: "A 3 song limited production album I wrote, produced, and recorded solo. Featuring a remaster of What Happens Next, plus two new songs.",
  },
  {
    id: 13,
    type: 'code',
    date: '1/23/2024',
    title: 'Portfolio website',
    link: 'https://github.com/kaydenhardcastle/kaydenhardcastle.github.io',
    description: "The code repo for this website.",
  },
]
